from __future__ import annotations


TRACE_SCHEMA_VERSION = "2.0"
DEBUG_TRACE_SCHEMA_VERSION = "1.0"

EVENT_STAGES = {
    "session_started": "session",
    "effective_config_snapshot": "session",
    "problem_parsed": "parsing",
    "problem_obligations_planned": "verification",
    "route_planned": "routing",
    "reasoning_state_initialized": "reasoning",
    "autonomous_solver_planned": "reasoning",
    "autonomous_agent_action": "reasoning",
    "autonomous_stall_detected": "reasoning",
    "autonomous_turn_failed": "reasoning",
    "round_summary": "reasoning",
    "reasoning_loop_completed": "reasoning",
    "skills_selected": "skill_selection",
    "tool_feedback_completed": "evidence",
    "agent_tool_request_completed": "evidence",
    "resource_plan_created": "orchestration",
    "resource_plan_updated": "orchestration",
    "adaptive_fanout_decided": "orchestration",
    "agent_protocol": "orchestration",
    "agent_created": "agent_lifecycle",
    "task_assigned": "agent_lifecycle",
    "model_turn_started": "agent_lifecycle",
    "model_turn_completed": "agent_lifecycle",
    "artifact_published": "communication",
    "message_sent": "communication",
    "message_delivered": "communication",
    "message_consumed": "communication",
    "agent_stopped": "agent_lifecycle",
    "retrieval_completed": "retrieval",
    "frozen_lemma_cache": "retrieval",
    "candidate_generation_started": "candidate_generation",
    "candidate_generated": "candidate_generation",
    "candidate_generation_failed": "candidate_generation",
    "candidate_fanout_completed": "candidate_generation",
    "candidate_pool_initialized": "peer_review",
    "peer_review_trigger_decided": "peer_review",
    "candidate_pool_registration_failed": "peer_review",
    "peer_review_started": "peer_review",
    "peer_review_completed": "peer_review",
    "rebuttal_started": "peer_review",
    "rebuttal_completed": "peer_review",
    "solver_peer_review_phase_completed": "peer_review",
    "shadow_probe_completed": "candidate_generation",
    "candidate_evidence_completed": "evidence",
    "hard_evidence_gate": "evidence",
    "verifier_completed": "verification",
    "new_branch_started": "verification",
    "new_branch_completed": "verification",
    "final_audit_started": "verification",
    "final_audit_completed": "verification",
    "audit_reentry_decision": "verification",
    "proof_completion_gate": "verification",
    "proof_status_finalized": "verification",
    "proof_obligations_generated": "verification",
    "candidate_conflict_matrix": "verification",
    "tool_checks": "evidence",
    "lemma_loop_completed": "lemma",
    "llm_lemma_curator_completed": "lemma",
    "lemma_request_completed": "lemma",
    "agent_replan_completed": "routing",
    "candidate_partial_recovery_started": "candidate_generation",
    "proof_token_canary_degraded": "candidate_generation",
    "expanded_candidates_reverified": "verification",
    "repair_proposed": "repair",
    "repair_actionability_gate": "repair",
    "repair_completed": "repair",
    "repair_committed": "repair",
    "repair_rolled_back": "repair",
    "candidate_arbitrated": "arbitration",
    "decision_committed": "arbitration",
    "candidate_final_states": "arbitration",
    "candidate_salvaged": "arbitration",
    "proof_graph_completed": "evidence",
    "final_answer_selected": "finalization",
    "finalization_completed": "finalization",
    "primary_completed": "finalization",
    "model_transport_completed": "transport",
    "case_trace_summary": "finalization",
    "closed_loop_health": "finalization",
    "budget_summary": "finalization",
    "answer_validation_warning": "finalization",
    "deadline_finalize": "deadline",
    "background_tail_audit": "deadline",
    "compression_validated": "context",
    "context_view_built": "context",
    "context_budget_infeasible": "context",
    "fallback_used": "fallback",
    "per_case_wall_clock_timeout": "deadline",
    "case_execution_failed": "completion",
    "run_completed": "completion",
    "formal_entry_compatibility": "completion",
    "phase_transition": "state",
}

JUDGE_EVENTS = frozenset(EVENT_STAGES)

PROTECTED_TRACE_EVENTS = frozenset(
    {
        "session_started",
        "effective_config_snapshot",
        "problem_parsed",
        "problem_obligations_planned",
        "route_planned",
        "reasoning_state_initialized",
        "autonomous_solver_planned",
        "round_summary",
        "reasoning_loop_completed",
        "llm_lemma_curator_completed",
        "lemma_request_completed",
        "candidate_partial_recovery_started",
        "proof_token_canary_degraded",
        "skills_selected",
        "tool_feedback_completed",
        "resource_plan_created",
        "resource_plan_updated",
        "adaptive_fanout_decided",
        "agent_protocol",
        "frozen_lemma_cache",
        "candidate_generation_started",
        "candidate_generated",
        "candidate_generation_failed",
        "candidate_pool_initialized",
        "solver_peer_review_phase_completed",
        "shadow_probe_completed",
        "candidate_evidence_completed",
        "candidate_conflict_matrix",
        "new_branch_started",
        "new_branch_completed",
        "final_audit_started",
        "final_audit_completed",
        "audit_reentry_decision",
        "repair_proposed",
        "repair_actionability_gate",
        "repair_completed",
        "hard_evidence_gate",
        "proof_obligations_generated",
        "proof_status_finalized",
        "candidate_final_states",
        "candidate_salvaged",
        "proof_graph_completed",
        "background_tail_audit",
        "case_execution_failed",
        "candidate_arbitrated",
        "decision_committed",
        "final_answer_selected",
        "model_transport_completed",
        "case_trace_summary",
        "closed_loop_health",
        "budget_summary",
        "fallback_used",
        "deadline_finalize",
        "run_completed",
        "formal_entry_compatibility",
    }
)
