from __future__ import annotations


TRACE_SCHEMA_VERSION = "2.0"
DEBUG_TRACE_SCHEMA_VERSION = "1.0"

EVENT_STAGES = {
    "session_started": "session",
    "effective_config_snapshot": "session",
    "problem_parsed": "parsing",
    "problem_obligations_planned": "verification",
    "route_planned": "routing",
    "reasoning_state_initialized": "reasoning",
    "long_horizon_planned": "reasoning",
    "round_summary": "reasoning",
    "reasoning_loop_completed": "reasoning",
    "skills_selected": "skill_selection",
    "tool_feedback_completed": "evidence",
    "call_allocation_planned": "orchestration",
    "call_allocation_rebalanced": "orchestration",
    "adaptive_fanout_decided": "orchestration",
    "retrieval_completed": "retrieval",
    "frozen_lemma_cache": "retrieval",
    "candidate_generation_started": "candidate_generation",
    "candidate_generated": "candidate_generation",
    "candidate_generation_failed": "candidate_generation",
    "candidate_fanout_completed": "candidate_generation",
    "shadow_probe_completed": "candidate_generation",
    "candidate_evidence_completed": "evidence",
    "hard_evidence_gate": "evidence",
    "verifier_completed": "verification",
    "proof_completion_gate": "verification",
    "proof_obligations_generated": "verification",
    "candidate_conflict_matrix": "verification",
    "tool_checks": "evidence",
    "lemma_loop_completed": "lemma",
    "expanded_candidates_reverified": "verification",
    "repair_proposed": "repair",
    "repair_actionability_gate": "repair",
    "repair_completed": "repair",
    "candidate_arbitrated": "arbitration",
    "candidate_final_states": "arbitration",
    "candidate_salvaged": "arbitration",
    "proof_graph_completed": "evidence",
    "final_answer_selected": "finalization",
    "finalization_completed": "finalization",
    "primary_completed": "finalization",
    "model_transport_completed": "transport",
    "case_trace_summary": "finalization",
    "closed_loop_health": "finalization",
    "budget_summary": "finalization",
    "answer_validation_warning": "finalization",
    "deadline_finalize": "deadline",
    "background_tail_audit": "deadline",
    "compression_validated": "context",
    "context_view_built": "context",
    "context_budget_infeasible": "context",
    "fallback_used": "fallback",
    "per_case_wall_clock_timeout": "deadline",
    "case_execution_failed": "completion",
    "run_completed": "completion",
    "phase_transition": "state",
}

JUDGE_EVENTS = frozenset(EVENT_STAGES)

PROTECTED_TRACE_EVENTS = frozenset(
    {
        "session_started",
        "effective_config_snapshot",
        "problem_parsed",
        "problem_obligations_planned",
        "route_planned",
        "reasoning_state_initialized",
        "long_horizon_planned",
        "round_summary",
        "reasoning_loop_completed",
        "skills_selected",
        "tool_feedback_completed",
        "call_allocation_planned",
        "call_allocation_rebalanced",
        "adaptive_fanout_decided",
        "frozen_lemma_cache",
        "candidate_generation_started",
        "candidate_generated",
        "candidate_generation_failed",
        "shadow_probe_completed",
        "candidate_evidence_completed",
        "candidate_conflict_matrix",
        "repair_proposed",
        "repair_actionability_gate",
        "repair_completed",
        "hard_evidence_gate",
        "proof_obligations_generated",
        "candidate_final_states",
        "candidate_salvaged",
        "proof_graph_completed",
        "background_tail_audit",
        "case_execution_failed",
        "candidate_arbitrated",
        "final_answer_selected",
        "model_transport_completed",
        "case_trace_summary",
        "closed_loop_health",
        "budget_summary",
        "fallback_used",
        "deadline_finalize",
        "run_completed",
    }
)
